const styles = {
 
  feedback: {
    margin: "1rem",
    fontSize: "3rem",
    minHeight: "1.5em",
    textAlign: "center",
  },

  title: {
    fontSize: "4rem",
    fontWeight: "900",
    marginTop: "1.5rem",
    marginBottom: "2.5rem",
    textAlign: "center",
    color: "#f37021",
    fontFamily: "'Baloo 2', 'Comic Sans MS', 'Comic Sans', cursive",
    lineHeight: "1.05",
    letterSpacing: "0.5px",
    textShadow: "none",
  },
 
  buttonRow: {
    display: "flex",
    justifyContent: "center",
    gap: "1.1rem",
    marginBottom: "3.5rem",
    marginTop: "2.5rem",
    overflowX: "auto",
    padding: "0 2rem",
  },
   container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    backgroundColor: "#ffffff",
    fontFamily: "'Arial', sans-serif",
  },
  title: {
    fontSize: "2rem",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: "1rem",
    color: "#000000",
  },
  mistakeCounter: {
    fontSize: "1rem",
    fontWeight: "bold",
    color: "#ff1744",
    marginBottom: "1rem",
  },
  answerRow: {
    display: "flex",
    justifyContent: "center",
    gap: "0.5rem",
    marginBottom: "1.5rem",
  },
  answerBox: {
    width: "3rem",
    height: "3rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.5rem",
    fontWeight: "bold",
    borderRadius: "0.5rem",
    backgroundColor: "#f0f0f0",
    border: "1px solid #cccccc",
    cursor: "pointer",
  },
  numberButton: {
    width: "3rem",
    height: "3rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.5rem",
    fontWeight: "bold",
    borderRadius: "50%",
    backgroundColor: "#ffffff",
    border: "1px solid #cccccc",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  resetButton: {
    marginTop: "1.5rem",
    padding: "0.8rem 2rem",
    fontSize: "1rem",
    fontWeight: "bold",
    color: "#000000",
    backgroundColor: "rgba(219, 219, 219, 0.2)",
    border: "none",
    borderRadius: "0.5rem",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(219, 219, 219, 0.2)",
  },
};

export default styles;